name: Test build

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
